[package]
name = "sheepit"
description = "A simple rust tool for releasing projects 🚀"

edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/ncipollo/sheepit"
version = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.17.2"
sequoia-openpgp = "1.16.0"
shellexpand = "3.1.0"
tempfile = "3"

[dev-dependencies]
mockall = "0.11.4"
